name: resuable
on:
  workflow_call:
    inputs:
      artifacts-download:
        description: 'Artifacts to download'
        required: true
        default: 'dist'
        type: string
    secrets:
      MY-PRECIOUS:
        description: 'some dummy secret'
        required: true
    outputs:
      result:
        description: 'The result of the workflow'
        value: ${{ jobs.build.outputs.outcome }}

jobs:
  build:
    outputs:
      outcome: ${{ steps.my_id.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.artifacts-download }}
      - name: echo secrets
        run: echo ${{ secrets.MY-PRECIOUS }}
      - name: Echo output
        run: ls
      - name: Echo Something
        run: echo "Hello from reusable workflow"
      - name: Set Result output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
        id: my_id

